---
title: "Supp_Files"
output: html_document
date: "2023-04-22"
---

#Supplementary Files
## PCA rds object:
-see Table 1 above
-Gene symbols instead of gene IDs

MD5 (PCA_919x919_matrix.rds) = 4fb295b106013b7915559eac6e2c8b6d >> apr 20 2023 (copy and pasted from above)

## 14 best scoring trees
```{r}
library(devtools)
library(ape) #write.tree
setwd("~/repo/cellphylo/")
load_all()

multiphylo_best_trees <- combine_multi_trees("~/repo/aqhumor/AqHum_5Species/aqhumor_final/jumble/54_jumble_search/best_trees/best_trees_dir/")

write.tree(multiphylo_best_trees, "best_scoring_jumble_trees_raw.tre", tree.names=TRUE)

```

input:
MD5 (best_trees_dir.tar.gz) = f9cdd3ec86a791c293d62a9ac878a2ee

output:
MD5 (best_scoring_jumble_trees_raw.tre) = ade813702b675b2325da1d4378d56002 >> fig 4 focal phylogeny is tree 2
MD5 (best_scoring_jumble_trees_Mah&Dunn2023.tre) = e225aaf3e5618bbc0a5b4df93c520d48 >> edited so that fig 4 focal phylogeny is tree 1. Use for publication

## Gene loadings
MD5 (FileS3_positive_loading_gene_descriptions_Mah&Dunn2023.tsv) = f4115eab49c7117772ef7f1f37baf4e2
MD5 (FileS4_negative_loading_gene_descriptions_Mah&Dunn2023.tsv) = 3ff5b081b1202243c55c14adfb2ecc99
-identical files to negative_NCBI_gene_descriptions.tsv and positive_NCBI_gene_descriptions.tsv but with name changed

MD5 (FileS5_gene_loadings_cell_signals_21Apr2023.tsv) = 3041b5c575fae08194d1dbb4e84b40e9 >> will likely change
### SUPPLEMENTARY PDF WITH ALL SUPPLEMENTARY FIGURES ###
#README
##Supplementary Files
File_name	Description
README	This file. A description of each supplementary file.

FileS1_PCA_919x919_matrix.rds	R object produced by PCA (Fig. S1, step 7) of the 919 cell 2000 genes matrix (Fig. S1, step 6). The 'x' slot contains a 919 cell 919 PC matrix that was used for downstream analyses (Fig. S1, step 7)

FileS2_best_scoring_jumble_trees_Mah&Dunn2023.tsv	The 14 highest scoring jumble trees that were tied for 'best tree'. Tree 1 was chosen as the focal phylogeny (Fig. 4).

FileS3_positive_loading_gene_descriptions_Mah&Dunn2023.tsv	TSV table of the top 10 most positively loaded genes for the first 20 PCs, with their HGNC gene symbol, HGNC full gene name and NCBI gene database summary provided.

FileS4_negative_loading_gene_descriptions_Mah&Dunn2023.tsv	TSV table of the top 10 most negatively loaded genes for the first 20 PCs, with their HGNC gene symbol, HGNC full gene name and NCBI gene database summary provided.

FileS5_gene_loadings_cell_signals	TSV table listing genes contributing to the cell signals in the positive or negative loadings of the first 10 PCs. References in support of specific gene functions are included. 

