---
title: "R Notebook"
output: html_notebook
---

My workflow
```{r}
min_cells = 3
min_features = 200
k_weight=100
n_pcs=30
UMAP_dim = c(1:30)
FindNeighbors_dim=c(1:30)
FindClusters_res = 0.5
print=TRUE

seurat.obj <- LoadData("ifnb")

mat <- seurat.obj[["RNA"]]@counts

#qc may have filtered out cells. Remove missing cells from mat
  #seurat cells - the cells in the seurat object that survived filtering min.cells=3, min.features=200
  seurat_cells <- seurat.obj@assays[["RNA"]] %>% colnames()
  filtered_mat <- mat[,which(colnames(mat) %in% seurat_cells)]


  ### Annotate Seurat object with species, sample, cluster id,  cell type.

  #parse out annotations from the cell ids
  #species_id <- sapply(strsplit(colnames(filtered_mat), "_"), function(v){return(v[1])})
  #sample_id <- sapply(strsplit(colnames(filtered_mat), "_"), function(v){return(v[2])})
  #cluster_id <- sapply(strsplit(colnames(filtered_mat), "_"), function(v){return(v[3])})
  #cell_type_id <- sapply(strsplit(colnames(filtered_mat), "_"), function(v){return(v[4])})
  #broad_cell_type_id <- sapply(strsplit(cell_type_id, "-"), function(v){return(v[1])})

  #Add annotation to Seurat obj
  #seurat.obj <- AddMetaData(seurat.obj, species_id, col.name="species_id")
  #seurat.obj <- AddMetaData(seurat.obj, sample_id, col.name = "sample_id")
  #seurat.obj <- AddMetaData(seurat.obj, cluster_id, col.name = "cluster_id")
  #seurat.obj <- AddMetaData(seurat.obj, cell_type_id, col.name = "cell_type_id")
  #seurat.obj <- AddMetaData(seurat.obj, broad_cell_type_id, col.name = "broad_cell_type_id")

  #seurat.obj@meta.data

  #mix up metadata - doesn't change order of seurat.obj.list
  #metadata.df <- seurat.obj@meta.data
  #CTRL <- metadata.df[metadata.df$orig.ident=="IMMUNE_CTRL",]
  #STIM <- metadata.df[metadata.df$orig.ident=="IMMUNE_STIM",]

  #reordered <- rbind(STIM,CTRL)
  #seurat.obj@meta.data <- reordered
  
  ### Integrate
  seurat.obj.list <- SplitObject(seurat.obj, split.by = "orig.ident")
  #seurat.obj.list <- c(IMMUNE_STIM=seurat.obj.list$IMMUNE_STIM, IMMUNE_CTRL=seurat.obj.list$IMMUNE_CTRL)

  features <- SelectIntegrationFeatures(object.list = seurat.obj.list)

  anchors <- FindIntegrationAnchors(object.list = seurat.obj.list, anchor.features = features)

  #repeatable no matter what object you choose.
  seurat.obj.example <- seurat.obj.list[[1]]
  all_genes <- seurat.obj.example@assays[["RNA"]] %>% row.names()

  combined <- IntegrateData(anchorset = anchors, k.weight=k_weight, features.to.integrate = all_genes)


  combined<- ScaleData(combined, verbose=FALSE)
  combined<- RunPCA(combined, npcs=n_pcs, verbose=FALSE)
  combined<- RunUMAP(combined, reduction = "pca", dims=UMAP_dim)
  combined<- FindNeighbors(combined, reduction = "pca", dims = FindNeighbors_dim)
  combined<- FindClusters(combined, resolution=FindClusters_res)

  integrated<- combined[["integrated"]]@scale.data
  integrated <- as.sparse(integrated)

  #Save data
  saveRDS(combined, "cross_species_integrated_ifnb_STIM_first.rds")

  #compare
  integrated_rand <- integrated
  combined_orig <- readRDS("ifnb/ifnb_orig/cross_species_integrated_ifnb_orig.rds")
  integrated_orig <- combined_orig[["integrated"]]@scale.data
  #reorder new to old
  rows <-rownames(integrated_orig)
  cols <- colnames(integrated_orig)
  integrated_rand_reordered <- integrated_rand[rows, cols]
  #View
  View(integrated_orig[1:10, 1:10])
  View(as.matrix(integrated_rand[1:10, 1:10]))
  View(as.matrix(integrated_rand_reordered[1:10, 1:10]))
  
  #produces different results!!! integrated_orig vs integrated_rand_reordered eg. 0.72585590 vs -0.02779077
```

Test with current Seurat workflow
```{r}
library(Seurat)
library(SeuratData)
library(patchwork)

# install dataset
InstallData("ifnb")

# load dataset
LoadData("ifnb")

# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.list <- SplitObject(ifnb, split.by = "stim")

###HERE###
#change the order of ifnb.list
#ifnb.list <- c(STIM=ifnb.list$STIM, CTRL=ifnb.list$CTRL)
###CLOSE###

# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = ifnb.list)

immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features)

# this command creates an 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)

# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)


saveRDS(immune.combined, "tutorial_ifnb_CTRL_first_2.rds")
#saveRDS(immune.combined, "tutorial_ifnb_STIM_first_2.rds")

```

```{r}
  #inspect
  CTRL_first <- readRDS("tutorial_ifnb_CTRL_first_2.rds")
  CTRL_integrated <- CTRL_first[["integrated"]]@scale.data
  rows <-rownames(CTRL_integrated)
  cols <- colnames(CTRL_integrated)
  
  STIM_first <-  readRDS("tutorial_ifnb_STIM_first_2.rds")
  STIM_integrated <- STIM_first[["integrated"]]@scale.data
  STIM_integrated_reorder <- STIM_integrated[rows, cols]
  
  #compare
  View(CTRL_integrated)
  View(STIM_integrated_reorder)
  
  
#did log normalization so check data slot of "integrated"
  CTRL_first <- readRDS("tutorial_ifnb_CTRL_first_2.rds")
  CTRL_integrated_dat <- CTRL_first[["integrated"]]@data
  rows <-rownames(CTRL_integrated_dat)
  cols <- colnames(CTRL_integrated_dat)
  
  STIM_first <-  readRDS("tutorial_ifnb_STIM_first_2.rds")
  STIM_integrated_dat <- STIM_first[["integrated"]]@data
  STIM_integrated_reorder_dat <- STIM_integrated_dat[rows, cols]
  
  View(as.matrix(CTRL_integrated_dat))
  View(as.matrix(STIM_integrated_reorder_dat))
  
  #eg.
  CTRL_integrated_dat["HBB", "AAACATACATTTCC.1"] #-0.06415531
  STIM_integrated_reorder_dat["HBB", "AAACATACATTTCC.1"] #0.02116652
```
