#!/bin/bash

#run Jumble in parallel
#only want to set up directories once
#need 1 empty outfile and outtree so you can indicate indiividual names for output files

cd /contml

mkdir outtrees_54mean_20PC_afterPCA_jumble_search
mkdir outfiles_54mean_20PC_afterPCA_jumble_search

touch outfile
touch outtree

echo "jumble preliminaries complete"

#send in the command
#printf './script.sh &%.0s' {1..50} and copy and paste below. Remove last `&`. #chatgpt

#run the script 50 times in parallel
./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh &./script_jumble_parallel_54mean_20PC_afterPCA.sh

echo "Commands complete"

exit
